### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by pennomi** [pennomi/openwest2015-twitter-clone#1]
- [ ] Various Tasks
  - [ ] Create Izeni Group on GitHub
  - [x] Create repositories
  - [x] Email Steve about class schedule
- [ ] Code
  - [ ] Django
    - [x] Models
    - [x] Parser
    - [x] Views
    - [x] Templates
    - [x] Login (KC)
    - [x] Register (KC)
    - [x] Links for hashtags/mentions (KC)
    - [ ] More general navigation links (KC)
  - [ ] DRF
    - [ ] Serializers
    - [ ] Viewsets & Routers
    - [ ] Permissions/Authentications
  - [ ] Angular
    - [ ] No Gulp at all (static files served by Django)
    - [ ] Services
    - [ ] UI Routes
    - [ ] Directives
- [ ] Slides
  - [ ] Django (Thane)
  - [ ] DRF (Thane)
  - [ ] Angular (Darby)
- [ ] Deploy to a flatpage
